require('dotenv').config()
const express = require('express')
const cors =  require('cors')
const app = express()
const db = require('./database/database')
const propertyroute = require('./routes/property.route')
const quoteroute = require ('./routes/quote.route')

app.use(cors())
app.use(express.json())
app.use('/', propertyroute)
app.use('/',quoteroute )
app.listen(process.env.PORT,(res) =>{
  console.log(`Server is running on port ${process.env.PORT}`)
})